# rag_core.py
import os
import tiktoken
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate

class RagEngine:
    """
    restructured Ingestion and Querying Engine for RAG (Retrieval-Augmented Generation) by OOP
    """
    
    def __init__(self):
        """inicialize the base concept（model、chrome、prompt template）"""
        
        self.token_api = os.environ.get("DEEPSEEK_TOKEN")
        if not self.token_api:
            print("warning: no environment variable DEEPSEEK_TOKEN")
            
        print(" [RagEngine] is loading Embedding model (BAAI/bge-small-zh-v1.5)...")
        self.embedding_model = HuggingFaceEmbeddings(
            model_name="BAAI/bge-small-zh-v1.5",
            model_kwargs={'device': 'cpu'}
        )
        
        print("[RagEngine] is processing the local chromabase: ./chroma_db ...")
        self.vector_store = Chroma(
            persist_directory="./chroma_db",
            embedding_function=self.embedding_model
        )
        
        print("[RagEngine] connecting to the LLM (deepseek-v4-flash)...")
        self.llm = ChatOpenAI(
            model_name="deepseek-v4-flash",
            temperature=0.2,
            openai_api_key=self.token_api,
            openai_api_base="https://api.deepseek.com",
        )
        
        rag_prompt_template = """You are a helpful and strict corporate HR assistant. 
Use the following pieces of retrieved attendance policies to answer the user's question. 
If you don't know the answer or if the provided policy doesn't contain enough information, say that you cannot find the explicit answer in the policy. Do not try to make up an answer.

Retrieved Attendance Policies (Context):
----------------------------------
{context}
----------------------------------

User's Question: {question}

Your Professional Answer:"""

        self.prompt_template = PromptTemplate(
            template=rag_prompt_template,
            input_variables=["context", "question"]
        )
        print("[RagEngine] finish initialization，RAG core is ready！")

    @staticmethod #use staticmethod to avoid self parameter, since this method does not depend on instance attributes
    def _tokenizer_len(text: str) -> int:
        """calculate the number of tokens in a text string using tiktoken"""
        tokenizer = tiktoken.get_encoding("cl100k_base")
        tokens = tokenizer.encode(text, disallowed_special=())
        return len(tokens)

    def query(self, question: str) -> str:
        """
        Core Function 1: Knowledge Base Retrieval and Q&A
        Receive user queries and return plain-text answers generated by the large model based on the local knowledge base.
        """
        print(f"🔍 [RagEngine] Chroma is processing the question: '{question}'...")
        
        results = self.vector_store.similarity_search(question, k=5)  

        context_text = "\n\n".join([
            f"---[Chunk {i+1} ]---\n"
            f"Source File: {doc.metadata.get('source', 'Unknown')}\n"
            f"Content: \n{doc.page_content}"
            for i, doc in enumerate(results)
        ])

        print("[RagEngine] LLM is generating the answer...")
        final_prompt = self.prompt_template.format(context=context_text, question=question)
        answer = self.llm.invoke(final_prompt)
        
        return answer.content

    def upload_document(self, file_path: str):
        """
        Core Fuction 2: Dynamically upload documents and update the vector database.
        Receive a local file paht, reading,chunking and embedding the text into the vector database.
        """
        print(f"[RagEngine] is reading the file for incremental ingestion: {file_path}")
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                raw_text = f.read()
        except FileNotFoundError:
            raise FileNotFoundError(f"File not found: {file_path}")

        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=300,
            chunk_overlap=50,
            length_function=self._tokenizer_len,
            separators=["\n\n", "\n", "。", "！", "？", "，", " "]
        )

        filename = os.path.basename(file_path)
        docs = text_splitter.create_documents([raw_text], metadatas=[{"source": filename}])
        print(f"finish chunking, generates {len(docs)} chunks。")

        self.vector_store.add_documents(docs)
        print(f"new file '{filename}'  has been added to Chroma !")